export const USER = {
  FETCH: 'FETCH_USERINFO',
  FETCH_COMPLETED: 'FETCH_USERINFO_COMPLETED',
  AUTHENTICATE: 'USER_AUTHENTICATE',
  AUTHENTICATED: 'USER_AUTHENTICATED',
  NOT_AUTHENTICATED: 'USER_NOT_AUTHENTICATED',
};

export const SETS = {
  FETCH_ALL: 'FETCH_SETS',
  FETCH_ALL_COMPLETED: 'FETCH_SETS_COMPLETED',
};

export const CARDS = {
  FETCH: 'FETCH_CARDS',
  FETCH_COMPLETED: 'FETCH_CARDS_COMPLETED',
  FETCH_DETAIL: 'FETCH_CARD_DETAIL',
  FETCH_DETAIL_COMPLETED: 'FETCH_CARD_DETAIL_COMPLETED',
  CHANGE_VIEW: 'CARDS_CHANGE_VIEW',
};

export const COLLECTION = {
  ADDCARD: 'ADDCARD',
  ADDCARD_COMPLETED: 'ADDCARD_COMPLETED',
  REMOVECARD: 'REMOVECARD',
  REMOVECARD_COMPLETED: 'REMOVECARD_COMPLETED',
};
