export const USER = {
  FETCH: 'FETCH_USERINFO',
  FETCH_COMPLETED: 'FETCH_USERINFO_COMPLETED',
  AUTHENTICATE: 'USER_AUTHENTICATE',
  AUTHENTICATED: 'USER_AUTHENTICATED',
  NOT_AUTHENTICATED: 'USER_NOT_AUTHENTICATED',
  VIEW: 'VIEW_USERINFO',
  VIEW_COMPLETED: 'VIEW_USERINFO_COMPLETED',
};

export const SETS = {
  FETCH_ALL: 'FETCH_SETS',
  FETCH_ALL_COMPLETED: 'FETCH_SETS_COMPLETED',
};

export const CARDS = {
  FETCH: 'FETCH_CARDS',
  FETCH_COMPLETED: 'FETCH_CARDS_COMPLETED',
  FETCH_DETAIL: 'FETCH_CARD_DETAIL',
  FETCH_DETAIL_COMPLETED: 'FETCH_CARD_DETAIL_COMPLETED',
  CHANGE_VIEW: 'CARDS_CHANGE_VIEW',
};

export const COLLECTION = {
  UPDATECARD: 'UPDATECARD',
  UPDATECARD_COMPLETED: 'UPDATECARD_COMPLETED',
  REMOVECARD: 'REMOVECARD',
  REMOVECARD_COMPLETED: 'REMOVECARD_COMPLETED',
};

export const WISHLIST = {
  FETCH: 'FETCH_WISHLIST',
  FETCH_COMPLETED: 'FETCH_WISHLIST_COMPLETED',
  UPDATE: 'UPDATE_WISHLIST',
  UPDATE_COMPLETED: 'UPDATE_WISHLIST_COMPLETED',
};

export const TRANSACTION = {
  FETCH_ALL: 'FETCH_TRANSACTIONS',
  FETCH_ALL_COMPLETED: 'FETCH_TRANSACTIONS_COMPLETED',
};
